---
- hosts: 172.31.30.140
  become: yes
  tasks:
   - include_tasks: myfile.yml
   - name: copy static files into ansible nodes
     copy:
       src: mytestfile
       dest: /home/ubuntu/mysaticfile
   - name: install webserver 
     apt:
      name: apache2
      state: present
     notify: restartwebserver

   - name: copy dynamic files into ansible nodes
     template:
         src: myindex.j2
         dest: /var/www/html/index.html
     notify: restartwebserver

   - name: i want to downlod files from remote(internet) into nodes side
     get_url:
      url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes

   - name: i want to create folder
     file:
      path: /home/ubuntu/myfolder
      state: directory

  handlers: 
  - name: restartwebserver
    service: 
       name: apache2
       state: restarted
        
