---
- hosts: 172.31.30.140
  become: yes
  tasks:
   - include_tasks: myfile.yml
   - name: copy static files into ansible nodes
     copy:
       src: mytestfile
       dest: /home/ubuntu/mysaticfile
   