---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install webserver on ubuntu ansible nodes
    apt:
      name: "{{mywebserverpackonubuntu}}"
      state: present
    when: ansible_os_family== "Debian"


  - name: start webserver on ubuntu ansible nodes
    service:
      name: "{{mywebserverpackonubuntu}}"
      state: started 
    when: ansible_os_family== "Debian"
     

  
  - name: install webserver on RedHat ansible nodes
    yum:
      name: "{{mywebserverpackonRedhat}}"
      state: present
    when: ansible_os_family== "RedHat"

  - name: start webserver on redHat ansible nodes
    service:
      name: "{{mywebserverpackonRedhat}}"
      state: started
    when: ansible_os_family== "RedHat"
      
